/*
 * Copyright 2026 Dmytro Soloviov (soulaway)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cab.ml.juno.coordinator;

/**
 * EU AI Act, Article 50 transparency support.
 *
 * Article 50 requires that natural persons be notified they are interacting
 * with an AI system, unless this is already obvious from context. Juno is
 * infrastructure, not the deployed AI system itself, so the obligation falls
 * on the operator. This class gives operators the field and constants needed
 * to satisfy that obligation without building it themselves.
 *
 * Single source of truth for the disclosure field name, its default text, and
 * the request-level opt-out field name. Reused by {@link OpenAiChatHandler}
 * (blocking and streaming) and {@link InferenceApiServer} (native
 * {@code /v1/inference} endpoint) so the literal strings are not duplicated
 * across the API surface.
 */
public final class AiDisclosure {

	/** Response field name carrying the disclosure text. */
	public static final String FIELD_NAME = "x_juno_ai_disclosure";

	/** Request field name for the opt-out flag. */
	public static final String REQUEST_OPT_OUT_FIELD = "x_juno_disclosure";

	/** Default disclosure text included in the response when enabled. */
	public static final String DISCLOSURE_TEXT = "The replies are generated by an AI system.";

	private AiDisclosure() {
	}

	/**
	 * Resolves whether the disclosure field should be included in a response.
	 *
	 * Disclosure is enabled by default. The request-level opt-out exists for
	 * API-to-API integrations where no natural person is present to receive the
	 * notice, a case Article 50 does not cover. Only an explicit {@code false}
	 * disables it; a missing or {@code true} value keeps it on.
	 *
	 * @param requestedFlag value of the {@value #REQUEST_OPT_OUT_FIELD} request
	 *                      field, or {@code null} if the client did not send it
	 * @return {@code true} unless {@code requestedFlag} is explicitly
	 *         {@link Boolean#FALSE}
	 */
	public static boolean isEnabled(Boolean requestedFlag) {
		return !Boolean.FALSE.equals(requestedFlag);
	}
}